/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as BookRouteImport } from './routes/book'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MethodRouteImport } from './routes/method'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCheckinRouteImport } from './routes/app/checkin'
import { Route as AppLibraryRouteImport } from './routes/app/library'
import { Route as AppMessagesRouteImport } from './routes/app/messages'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppProgressRouteImport } from './routes/app/progress'
import { Route as AppScheduleRouteImport } from './routes/app/schedule'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as EnrollSlugRouteImport } from './routes/enroll/$slug'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as LibrarySlugRouteImport } from './routes/library/$slug'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as ProgramsSlugRouteImport } from './routes/programs/$slug'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioBuilderRouteImport } from './routes/studio/builder'
import { Route as StudioCheckinsRouteImport } from './routes/studio/checkins'
import { Route as StudioClientsRouteImport } from './routes/studio/clients'
import { Route as StudioScheduleRouteImport } from './routes/studio/schedule'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppTrainIdRouteImport } from './routes/app/train.$id'
import { Route as StudioClientsIdRouteImport } from './routes/studio/clients.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const EnrollSlugRoute = EnrollSlugRouteImport.update({
  id: '/enroll/$slug',
  path: '/enroll/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/library/$slug',
  path: '/library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioBuilderRoute = StudioBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioCheckinsRoute = StudioCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioClientsRoute = StudioClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioScheduleRoute = StudioScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StudioRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrainIdRoute = AppTrainIdRouteImport.update({
  id: '/train/$id',
  path: '/train/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const StudioClientsIdRoute = StudioClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudioClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/library': typeof AppLibraryRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/progress': typeof AppProgressRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/enroll/$slug': typeof EnrollSlugRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/studio/builder': typeof StudioBuilderRoute
  '/studio/checkins': typeof StudioCheckinsRoute
  '/studio/clients': typeof StudioClientsRouteWithChildren
  '/studio/schedule': typeof StudioScheduleRoute
  '/app/': typeof AppIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/train/$id': typeof AppTrainIdRoute
  '/studio/clients/$id': typeof StudioClientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/library': typeof AppLibraryRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/progress': typeof AppProgressRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/enroll/$slug': typeof EnrollSlugRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/studio/builder': typeof StudioBuilderRoute
  '/studio/checkins': typeof StudioCheckinsRoute
  '/studio/clients': typeof StudioClientsRouteWithChildren
  '/studio/schedule': typeof StudioScheduleRoute
  '/app': typeof AppIndexRoute
  '/library': typeof LibraryIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/train/$id': typeof AppTrainIdRoute
  '/studio/clients/$id': typeof StudioClientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/app/checkin': typeof AppCheckinRoute
  '/app/library': typeof AppLibraryRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/progress': typeof AppProgressRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/enroll/$slug': typeof EnrollSlugRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/studio/builder': typeof StudioBuilderRoute
  '/studio/checkins': typeof StudioCheckinsRoute
  '/studio/clients': typeof StudioClientsRouteWithChildren
  '/studio/schedule': typeof StudioScheduleRoute
  '/app/': typeof AppIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/train/$id': typeof AppTrainIdRoute
  '/studio/clients/$id': typeof StudioClientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/studio'
    | '/assessment'
    | '/book'
    | '/login'
    | '/method'
    | '/app/checkin'
    | '/app/library'
    | '/app/messages'
    | '/app/onboarding'
    | '/app/progress'
    | '/app/schedule'
    | '/app/settings'
    | '/enroll/$slug'
    | '/library/$slug'
    | '/programs/$slug'
    | '/studio/builder'
    | '/studio/checkins'
    | '/studio/clients'
    | '/studio/schedule'
    | '/app/'
    | '/library/'
    | '/programs/'
    | '/studio/'
    | '/api/auth/$'
    | '/app/train/$id'
    | '/studio/clients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/book'
    | '/login'
    | '/method'
    | '/app/checkin'
    | '/app/library'
    | '/app/messages'
    | '/app/onboarding'
    | '/app/progress'
    | '/app/schedule'
    | '/app/settings'
    | '/enroll/$slug'
    | '/library/$slug'
    | '/programs/$slug'
    | '/studio/builder'
    | '/studio/checkins'
    | '/studio/clients'
    | '/studio/schedule'
    | '/app'
    | '/library'
    | '/programs'
    | '/studio'
    | '/api/auth/$'
    | '/app/train/$id'
    | '/studio/clients/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/studio'
    | '/assessment'
    | '/book'
    | '/login'
    | '/method'
    | '/app/checkin'
    | '/app/library'
    | '/app/messages'
    | '/app/onboarding'
    | '/app/progress'
    | '/app/schedule'
    | '/app/settings'
    | '/enroll/$slug'
    | '/library/$slug'
    | '/programs/$slug'
    | '/studio/builder'
    | '/studio/checkins'
    | '/studio/clients'
    | '/studio/schedule'
    | '/app/'
    | '/library/'
    | '/programs/'
    | '/studio/'
    | '/api/auth/$'
    | '/app/train/$id'
    | '/studio/clients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
  BookRoute: typeof BookRoute
  LoginRoute: typeof LoginRoute
  MethodRoute: typeof MethodRoute
  EnrollSlugRoute: typeof EnrollSlugRoute
  LibrarySlugRoute: typeof LibrarySlugRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/checkin': {
      id: '/app/checkin'
      path: '/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/enroll/$slug': {
      id: '/enroll/$slug'
      path: '/enroll/$slug'
      fullPath: '/enroll/$slug'
      preLoaderRoute: typeof EnrollSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$slug': {
      id: '/library/$slug'
      path: '/library/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/builder': {
      id: '/studio/builder'
      path: '/builder'
      fullPath: '/studio/builder'
      preLoaderRoute: typeof StudioBuilderRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/checkins': {
      id: '/studio/checkins'
      path: '/checkins'
      fullPath: '/studio/checkins'
      preLoaderRoute: typeof StudioCheckinsRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/clients': {
      id: '/studio/clients'
      path: '/clients'
      fullPath: '/studio/clients'
      preLoaderRoute: typeof StudioClientsRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/schedule': {
      id: '/studio/schedule'
      path: '/schedule'
      fullPath: '/studio/schedule'
      preLoaderRoute: typeof StudioScheduleRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/train/$id': {
      id: '/app/train/$id'
      path: '/train/$id'
      fullPath: '/app/train/$id'
      preLoaderRoute: typeof AppTrainIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/studio/clients/$id': {
      id: '/studio/clients/$id'
      path: '/$id'
      fullPath: '/studio/clients/$id'
      preLoaderRoute: typeof StudioClientsIdRouteImport
      parentRoute: typeof StudioClientsRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppCheckinRoute: typeof AppCheckinRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProgressRoute: typeof AppProgressRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTrainIdRoute: typeof AppTrainIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCheckinRoute: AppCheckinRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProgressRoute: AppProgressRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppTrainIdRoute: AppTrainIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface StudioClientsRouteChildren {
  StudioClientsIdRoute: typeof StudioClientsIdRoute
}

const StudioClientsRouteChildren: StudioClientsRouteChildren = {
  StudioClientsIdRoute: StudioClientsIdRoute,
}

const StudioClientsRouteWithChildren = StudioClientsRoute._addFileChildren(
  StudioClientsRouteChildren,
)

interface StudioRouteRouteChildren {
  StudioBuilderRoute: typeof StudioBuilderRoute
  StudioCheckinsRoute: typeof StudioCheckinsRoute
  StudioClientsRoute: typeof StudioClientsRouteWithChildren
  StudioScheduleRoute: typeof StudioScheduleRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioBuilderRoute: StudioBuilderRoute,
  StudioCheckinsRoute: StudioCheckinsRoute,
  StudioClientsRoute: StudioClientsRouteWithChildren,
  StudioScheduleRoute: StudioScheduleRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  StudioRouteRoute: StudioRouteRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
  BookRoute: BookRoute,
  LoginRoute: LoginRoute,
  MethodRoute: MethodRoute,
  EnrollSlugRoute: EnrollSlugRoute,
  LibrarySlugRoute: LibrarySlugRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
